#!/usr/bin/perl -w
use strict;


## Run yoshimi headless
## Pass a name (used in MIDI and Jack identifiers) and an instrument file. 
my $name = shift or die;
my $instrument = shift or die;

## 
print " InitialiseYos is getting going....\n";
my $bin = `which yoshimi`;
chomp $bin;
-x $bin or die "Cannot find yoshimi";
my $cmd = "$bin  -i -J --alsa-midi=120Proof -c -K -L '$instrument' -N $name -R 48000";
# print "$cmd\n";
my $pid = fork();
if(!$pid){
    ## In child
    `$cmd `; # 2>&1 > /dev/null
}





## 
