#!/user/bin/perl -w
use strict;

## Mistress is the boss.  She is in charge.

## She calls the scripts, in the proper order, to set up 120Proof.

## InitialisePd To get Pure Data started

## InitialiseMidi where all the midi connections are defined


my $VERBOSE = shift;
defined $VERBOSE or $VERBOSE  = 1;

