#!/usr/bin/perl -w
use strict;

## Mistress is the boss.  It is in charge.
## It calls the scripts, in the proper order, to set up 120Proof.

## Required to run Jack
$ENV{"JACK_PROMISCUOUS_SERVER"} = 'jack';

## Required to run 120Proof
$0 =~ /^(.+)\/[^\/]+$/ or die $0;
$ENV{"Home120Proof"} = $1;
warn "120Proof's Mistress running rooted at: $ENV{'Home120Proof'}";

# Kill any old versions of what Mistress will start
`pgrep lpx_controll` and `pkill lpx_controll`;
warn "Killed";
# Set the mode of the LPX 
print `$ENV{"Home120Proof"}/lpx_mode 1`;
print `$ENV{"Home120Proof"}/lpx_mode 127`;
warn "Set LPX mode";
# Remove any nasty Jack MIDI connecvtions
print `$ENV{"Home120Proof"}/delete_jack_midi_connections delete`;
warn "Cleared Jack Midi";

## Run ModHost.  This will set up Jack MIDI
print "Initialise Mod-host\n";
print `$ENV{"Home120Proof"}/InitialiseModHost`;
print "Finished Initialisng mod-host\n";

## Set up the controls for the LPX
my $lpx_control_pid = fork();
if(!$lpx_control_pid){
    print `$ENV{"Home120Proof"}/lpx_controll`;
    exit(0);
}
warn "lpx_control running on pid: $lpx_control_pid";


## Run the pedal
my $pedal_pid = fork();
if(!$pedal_pid){
    my $driver_dir = "$ENV{Home120Proof}/pedal";
    print `$driver_dir/driver $ENV{Home120Proof}/PEDALS/pedal`;
    exit(0);
}
    


print "Whoami: " . `whoami`;
print "Groups: " . `groups`;
