#!/bin/bash

## Mistress is the boss.  She is in charge.

## She calls the scripts, in the proper order, to set up 120Proof.

## InitialisePd To get Pure Data started
./InitialisePd

## InitialiseModHost to get mod-host running
./InitialiseModHost
sleep 1
## InitialiseMidi where all the midi connections are defined
./InitialiseMidi


