#!/usr/bin/perl -w
use strict;
use lib("$ENV{'Home120Proof'}/Perl");
use One20Proof;

my $Home120Proof = $ENV{Home120Proof};

# `$hd` becomes path to this script
my ($hd) = $0 =~ /^(.+)\/[^\/]+$/ or die $!;
-d $hd or die "$! $hd"; 

## Set up midi file
my $midi_cfg = "$hd/midi.cfg";
-r $midi_cfg or die "$hd cannot read $midi_cfg";

my $init_midi = "$Home120Proof/bin/InitialiseMidi";
-x $init_midi or die "$!: $init_midi";

# The name of the directory this is in is the name of the instrument. 

my ( $instrument) = $hd =~ /\/([^\/]+)$/ or die $!;

# Idisyncratic part of script. Works for all drums
my $lpx_ctl = "$Home120Proof/Instruments/lpx_ctl/$instrument/Initialise";
-x $lpx_ctl or die "$!: $lpx_ctl ";

my $midi_sample = "$Home120Proof/Instruments/midi_sample/$instrument/Initialise";
-x $midi_sample or die "$!: $midi_sample ";

&One20Proof::run_daemon ($lpx_ctl );
&One20Proof::run_daemon($midi_sample);
print `$midi_sample`;
print `$lpx_ctl`;

# Always do MIDI last.  Wait for it to finish
&One20Proof::run_daemon("$init_midi $midi_cfg", 1);
&One20Proof::handle_jack("connect MidiSampleQzn3t:output system:playback_1");
